# tasks/main.yml



- name: install certbot dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates


- name: install Python cryptography module
  pip: name=cryptography


- name: download certbot
  become: yes
  become_user: '{{ deploy_user }}'
  get_url: >
    url=https://dl.eff.org/certbot-auto
    dest=/home/{{ deploy_user }}/certbot-auto


- name: check if we have generated a cert already
  stat: path=/etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert_stats

- name: generate certs first time
  become: yes
  become_user: '{{ deploy_user }}'
  become_method: sudo
  shell: "/home/{{ deploy_user }}/certbot-auto certonly --standalone {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
  when: cert_stats.stat.exists == False


- name: generate certs (subsequent time)
  become: yes
  become_user: '{{ deploy_user }}'
  become_method: sudo
  shell: "/home/{{ deploy_user }}/certbot-auto certonly --webroot -w /var/www/{{ domain }}/public {{ letsencrypt_domain_flags | join(' ') }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
  when: cert_stats.stat.exists == True

- name: Reload Nginx
  service: name=nginx state=reloaded
